export const GET_CATEGORY = "GET_CATEGORY"
export const SET_CATEGORY = "SET_CATEGORY"
export const SET_QUIZ = "SET_QUIZ"
export const GET_QUIZ = "GET_QUIZ"
export const REMOVE_QUIZ = "REMOVE_QUIZ"
export const SET_ISHOW = "SET_ISHOW"